DROP PROCEDURE IF EXISTS `usp_invoice_total`;
DELIMITER //
CREATE PROCEDURE `usp_invoice_total` ()
  LANGUAGE SQL
  NOT DETERMINISTIC
  CONTAINS SQL
  SQL SECURITY DEFINER
BEGIN
  SELECT 1 AS invoice_total;
END //
DELIMITER ;