DROP PROCEDURE IF EXISTS `usp_customer_lookup`;
DELIMITER //
CREATE PROCEDURE `usp_customer_lookup` ()
  LANGUAGE SQL
  NOT DETERMINISTIC
  CONTAINS SQL
  SQL SECURITY DEFINER
BEGIN
  SELECT 1 AS customer_id;
END //
DELIMITER ;